---
- name: Create directory structure for media stack
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ uid.stdout }}"
    group: "{{ gid.stdout }}"
  loop:
    - /opt/containers/actualbudget
    - /opt/containers/actualbudget/data

- name: Deploy docker-compose file from template
  template:
    src: docker-compose.yml.j2
    dest: /opt/containers/actualbudget/docker-compose.yml
    mode: '0644'

- name: Start the container stack
  community.docker.docker_compose_v2:
    project_src: /opt/containers/actualbudget
    state: present
