---
- name: Create directory for the application
  file:
    path: /opt/containers/traefik
    state: directory
    mode: '0755'

- name: Deploy docker-compose file from template
  template:
    src: docker-compose.yml.j2
    dest: /opt/containers/traefik/docker-compose.yml
    mode: '0644'

- name: Start the container stack
  community.docker.docker_compose_v2:
    project_src: /opt/containers/traefik
    state: present

